USE alpha_app;

CREATE TABLE IF NOT EXISTS ACCOUNT(
    RECORDNUM INT NOT NULL AUTO_INCREMENT,
    CPF VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ACCOUNTPASSWORD VARCHAR(255) NOT NULL,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (EMAIL)
    FOREIGN KEY (CPF) REFERENCES PERSON(CPF)
);