version: '3'

services:
    mysql:
      container_name: mysql
      build:
        dockerfile: ./database/dev.Dockerfile
        target: development
      restart : always
      ports:
        - 3333:3000
      env_file:
        - .env
    
    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      env_file:
        - .env
