USE alpha_app;

CREATE TABLE PERSON(
    RECORDNUM INT NOT NULL AUTO_INCREMENT,
    CPF VARCHAR(11) NOT NULL,
    FIRSTNAME VARCHAR(255) NOT NULL,
    LASTNAME VARCHAR(255) NOT NULL,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (CPF)
);